### ISSUE TITLE
Processing stops when "failed to determine file tagged status"

### ISSUE THREAD

**Issue by joewarmelink** [ccjensen/PlexMediaTagger#11]
I am using the following command nightly to update my library and import any changed/new files into my iTunes library:

/Users/joe/PlexMediaTagger/plexmediatagger.py -b --tag --add-to-itunes

A few of my movies are causing this error:

  processing 117/654 movies : A Charlie Brown Christmas (1965) ------------------------------------------------------------------------------------------------------------------
    processing 1/1 media_items
     processing 1/1 part_items
      Failed to determine file tagged status
Traceback (most recent call last):
  File "/Users/joe/PlexMediaTagger/plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "/Users/joe/PlexMediaTagger/plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/Users/joe/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/Users/joe/PlexMediaTagger/SectionProcessor.py", line 150, in process_movie_section_element
    threading.Thread(None, self.process_video(full_movie_item)).start()
  File "/Users/joe/PlexMediaTagger/SectionProcessor.py", line 205, in process_video
    video_item_processor.process()
  File "/Users/joe/PlexMediaTagger/VideoItemProcessor.py", line 401, in process
    if self.opts.tag and self.canTag(part_item) and self.shouldTag(part_item):
  File "/Users/joe/PlexMediaTagger/VideoItemProcessor.py", line 41, in shouldTag
    comment_tag_contents = self.getFileCommentTagContents(part_item)
  File "/Users/joe/PlexMediaTagger/VideoItemProcessor.py", line 103, in getFileCommentTagContents
    return nil
NameError: global name 'nil' is not defined

The problem is not necessarily that it couldn't process the movie and is having this issue, but that it stops processing all my files once it encounters this error once.  In this case, you can see that it stopped on 'C' of my movie library.

What is causing this issue?  And is there a way to continue processing files?

On a side note, is there a better way to contact you with these types of issues before I create an issue on GitHub for it?

**Comment by ccjensen** [comment]
Made a fix that I think will fix your issue. Could you get the latest version and give it another go?

**Comment by joewarmelink** [comment]
Thanks so much for the quick response on these issues!  That worked perfectly.  Keep up the good work!

**Comment by ccjensen** [comment]
np, thanks for reporting the issues!
