### ISSUE TITLE
A New Error since Plex Update

### ISSUE THREAD

**Issue by ArnaudFeld** [ccjensen/PlexMediaTagger#14]
I get this Error:

Traceback (most recent call last):
File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 297, in 
sys.exit(main())
File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 254, in main
section_processor.process_section(section_element)
File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
self.process_movie_section_element(section_element)
File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 141, in process_movie_section_element
selected_movie_items = self.get_selection_for_media_container_element(movies_media_container_element)
File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 67, in get_selection_for_media_container_element
list_of_items = [MovieItem(self.opts, item) for item in media_container_element.getchildren()]
File "/Volumes/Thor/PlexMediaTagger/Items/MovieItem.py", line 17, in __init_
self.media_items = [MediaItem(self.opts, self, media_element) for media_element in self.video.findall("Media")]
File "/Volumes/Thor/PlexMediaTagger/Items/MediaItem.py", line 23, in init
self.part_items = [PartItem(self.opts, self, part_element) for part_element in self.media_element.findall("Part")]
File "/Volumes/Thor/PlexMediaTagger/Items/PartItem.py", line 23, in init
self.file_path = normalize('NFC', unquote(file_path).decode('utf-8'))
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 55: ordinal not in range(128)_

Any Hints?

**Comment by ccjensen** [comment]
if you turn on verbose logging for the script, what is the output leading up to the error being thrown?

**Comment by ArnaudFeld** [comment]
> Processing section 1/1 : 'Disney' =================================================================================================================================================================================
    Get contents: http://localhost:32400/library/sections/7/all
Traceback (most recent call last):
  File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 141, in process_movie_section_element
    selected_movie_items = self.get_selection_for_media_container_element(movies_media_container_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 67, in get_selection_for_media_container_element
    list_of_items = [MovieItem(self.opts, item) for item in media_container_element.getchildren()]
  File "/Volumes/Thor/PlexMediaTagger/Items/MovieItem.py", line 17, in __init__
    self.media_items = [MediaItem(self.opts, self, media_element) for media_element in self.video.findall("Media")]
  File "/Volumes/Thor/PlexMediaTagger/Items/MediaItem.py", line 23, in __init__
    self.part_items = [PartItem(self.opts, self, part_element) for part_element in self.media_element.findall("Part")]
  File "/Volumes/Thor/PlexMediaTagger/Items/PartItem.py", line 23, in __init__
    self.file_path = normalize('NFC', unquote(file_path).decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 38: ordinal not in range(128)


This everything is see. But some Media-Libraries works and some other throw this error. It is not on all libraries.

**Comment by ccjensen** [comment]
hmmm, what's the command line you are using (what options, etc)?
If you look at the Disney section in that library, do you see items that contain "special" characters such as ö?

**Comment by ArnaudFeld** [comment]
This is the total command line which is use for starting Plexmediatagger.
`python /Volumes/Thor/PlexMediaTagger/plexmediatagger.py --username=MYPLEXUSER --password=MYPASSWORD -tvv --tag-tv-prefer-season-artwork`

i'm working on OSX (my Shell is ZSH).

Yes there are Special Characters like "ä" and "ö"

**Comment by ccjensen** [comment]
just as an experiment could you try running the script from a bash shell?

**Comment by ArnaudFeld** [comment]
with bash shell the same issue :(

**Comment by ccjensen** [comment]
This would probably be the easiest for me to figure out if I could reproduce the problem. Any chance you can help me figure out what media item is causing the problem? Alternatively sending me a `find .` listing of all the files in that media library and I can recreate it on my server.

**Comment by ArnaudFeld** [comment]
Can is send it to you via mail or Twitter DM?

**Comment by ccjensen** [comment]
twitter DM should work now, thanks!

**Comment by ArnaudFeld** [comment]
/bin/done :) i Hope it help you to find the bug or bugs

**Comment by nickp1972** [comment]
I have the same problem. I traced it to two movies in my library: Naked Gun 2 1/2, and Naked Gun 33 1/3 - in my case, the error refers to the 1/2 symbol (and when I remove that from the library, it then refers to the 1/3). Once both items have been removed from the library, Plex Media Tagger runs as beautifully as it's ever done.

In case this helps! Thanks for such a wonderful program, by the way.

**Comment by ccjensen** [comment]
thanks, nick. That is helpful. I will be trying to figure out a fix soonish. Stay tuned :)
