### ISSUE TITLE
Exec Format Error

### ISSUE THREAD

**Issue by Atorath** [ccjensen/PlexMediaTagger#22]
i get this Error on any file, i checked right on files i use Fedora 31 my call is 
python2.7 ./plexmediatagger.py -t -vvv -i [myIpAddress] --username=[MyUser] --password=[MybigSecret]
same happens if i call the above via sudo

output:
--------
processing 1/1 movies : White Wall (2010) ----------------------------------------------------------------------------------------------------------------------------------
    processing 1/1 media_items
     processing 1/1 part_items
       original path /mnt/plex/Movies/White Wall (2009).m4v
       modified path /mnt/plex/Movies/White Wall (2009).m4v
Traceback (most recent call last):
  File "./plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "./plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/home/adi/Downloads/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/home/adi/Downloads/PlexMediaTagger/SectionProcessor.py", line 150, in process_movie_section_element
    threading.Thread(None, self.process_video(full_movie_item)).start()
  File "/home/adi/Downloads/PlexMediaTagger/SectionProcessor.py", line 205, in process_video
    video_item_processor.process()
  File "/home/adi/Downloads/PlexMediaTagger/VideoItemProcessor.py", line 409, in process
    if self.opts.tag and self.canTag(part_item) and self.shouldTag(part_item):
  File "/home/adi/Downloads/PlexMediaTagger/VideoItemProcessor.py", line 42, in shouldTag
    comment_tag_contents = self.getFileCommentTagContents(part_item)
  File "/home/adi/Downloads/PlexMediaTagger/VideoItemProcessor.py", line 99, in getFileCommentTagContents
    result = subprocess.Popen(get_tags_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

any hint what is wrong here ?

**Comment by ccjensen** [comment]
I think the problem is the `SublerCLI` tool is not working correctly. Can you try running it manually and see if it complains about the platform/OS not being compatible or just crashes?

**Comment by Atorath** [comment]
i execute:
./SublerCLI
and get this:
bash: ./SublerCLI: cannot execute binary file: Exec format error

OMG -- this is for OSX .. not linux . .my bad

**Comment by ccjensen** [comment]
no worries. The python is written so that it should work on linux too, but the binary that embeds the metadata is macOS. If you can find one that works on linux you should be able to tweak the script pretty easily to work on linux
