### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by Tigrecito** [ccjensen/PlexMediaTagger#8]
hi ccjensen,

the authentication thing now works like a charm. unfortunately I got another issue. 
I tried to remove all tags from a file (and also tried to tag another file) .. both times I got this output after selecting the file - and nothing seemed to change:

    processing 1/1 media_items
     processing 1/1 part_items
     removing tags...
Traceback (most recent call last):
  File "plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 150, in process_movie_section_element
    threading.Thread(None, self.process_video(full_movie_item)).start()
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 205, in process_video
    video_item_processor.process()
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 399, in process
    self.remove_tags(part_item)
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 165, in remove_tags
    success = self.execute_command(filepath, tag_removal_cmd, action_description)
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 126, in execute_command
    result = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, preexec_fn = self.preexec).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ccjensen** [comment]
could you rerun the script but add on -vv to enable debug logging, and then return back here with the output?

**Comment by Tigrecito** [comment]
for example this command:

python plexmediatagger.py -t --tag-tv-prefer-season-artwork -o -vv --username=?????? --password=????? -f

leads to this output:

I can properly select a mp4 movie (the same happens with many different movies, I tried.. all of them already used to work with the last version of your tagger !
......

Item # to select $10
    Get contents: http://localhost:32400/library/metadata/28225
  processing 1/1 movies : Das Lied von den zwei Pferden (2010) ------------------------------------------------------------
    processing 1/1 media_items
     processing 1/1 part_items
      original path /Volumes/Media/Media Plex/Filme Dokumentation/Das Lied von den zwei Pferden (2010) - 720p.mp4
      modified path /Volumes/Media/Media Plex/Filme Dokumentation/Das Lied von den zwei Pferden (2010) - 720p.mp4
     tagging...
          Downloading artwork...
           saving artwork to /var/folders/k_/d7z2xmp95hx3wdcvbv7vh5b00000gs/T/Das Lied von den zwei Pferden (2010).jpg
      'Tags added and optimized' arguments: ['/Users/Administrator/Desktop/PlexMediaTagger/SublerCLI-v010', '-O', '-t', u'{Comments:I_T_U_N_E_S::::R_0::::PC_1::::D_1419308678}{Artwork:/var/folders/k_/d7z2xmp95hx3wdcvbv7vh5b00000gs/T/Das Lied von den zwei Pferden (2010).jpg}{Media Kind:Movie}{Name:Das Lied von den zwei Pferden}{Artist:Byambasuren Davaa}{Genre:Dokumentarfilm}{Release Date:2010-06-03}{Description:Ein Versprechen, eine alte, zerst\xf6rte Pferdekopfgeige und ein verloren geglaubtes Lied f\xfchren die S\xe4ngerin Urna in die \xc4u\xdfere Mongolei zur\xfcck. Ihre Gro\xdfmutter musste einst ihre geliebte Geige in den Wirren der chinesischen Kulturrevolution zerst\xf6ren. Auf dem Geigenhals war das uralte Lied der Mongolen, \u201eDie zwei Pferde des Dschingis Khan\u201c, eingraviert. Nur Hals und Kopf der Geige \xfcberlebten den Kultursturm. Nun ist es an der Zeit, das Versprechen, das Urna ihrer Gro\xdfmutter gab, einzul\xf6sen.  Angekommen in Ulaanbaatar bringt Urna die noch erhaltenen Teile der Geige - Kopf und Hals - zu Hicheengui, einem bekannten Pferdekopfgeigenbauer, der dem alten Instrument einen neuen K\xf6rper bauen soll. Danach bricht Urna ins Hinterland auf, um dort die fehlenden Strophen des Lieds zu suchen. Doch sie wird entt\xe4uscht. Keiner der Menschen, denen sie auf ihrem Weg begegnet, scheint die alte Weise der Mongolen noch zu kennen \u2026}{Long Description:Ein Versprechen, eine alte, zerst\xf6rte Pferdekopfgeige und ein verloren geglaubtes Lied f\xfchren die S\xe4ngerin Urna in die \xc4u\xdfere Mongolei zur\xfcck. Ihre Gro\xdfmutter musste einst ihre geliebte Geige in den Wirren der chinesischen Kulturrevolution zerst\xf6ren. Auf dem Geigenhals war das uralte Lied der Mongolen, \u201eDie zwei Pferde des Dschingis Khan\u201c, eingraviert. Nur Hals und Kopf der Geige \xfcberlebten den Kultursturm. Nun ist es an der Zeit, das Versprechen, das Urna ihrer Gro\xdfmutter gab, einzul\xf6sen.  Angekommen in Ulaanbaatar bringt Urna die noch erhaltenen Teile der Geige - Kopf und Hals - zu Hicheengui, einem bekannten Pferdekopfgeigenbauer, der dem alten Instrument einen neuen K\xf6rper bauen soll. Danach bricht Urna ins Hinterland auf, um dort die fehlenden Strophen des Lieds zu suchen. Doch sie wird entt\xe4uscht. Keiner der Menschen, denen sie auf ihrem Weg begegnet, scheint die alte Weise der Mongolen noch zu kennen \u2026}{Rating:}{Cast:Urna Chahar-Tugchi, Hicheengui Sambuu, Chimed Dolgor}{Director:Byambasuren Davaa}{Screenwriters:Byambasuren Davaa}{Studio:Bayerischer Rundfunk}{HD Video:1}', '-i', u'/Volumes/Media/Media Plex/Filme Dokumentation/Das Lied von den zwei Pferden (2010) - 720p.mp4']
Traceback (most recent call last):
  File "plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 150, in process_movie_section_element
    threading.Thread(None, self.process_video(full_movie_item)).start()
  File "/Users/Administrator/Desktop/PlexMediaTagger/SectionProcessor.py", line 205, in process_video
    video_item_processor.process()
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 403, in process
    self.tag(part_item)
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 211, in tag
    success = self.execute_command(filepath, tag_cmd, action_description)
  File "/Users/Administrator/Desktop/PlexMediaTagger/VideoItemProcessor.py", line 126, in execute_command
    result = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, preexec_fn = self.preexec).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ccjensen** [comment]
And I'm guessing if you run:
ls '/Volumes/Media/Media Plex/Filme Dokumentation/Das Lied von den zwei Pferden (2010) - 720p.mp4'
It shows that it is a valid file path on that machine?

**Comment by Tigrecito** [comment]
right.. the ls command shows the file.. the file and path are valid on that machine (which also runs pjs server !)

**Comment by Tigrecito** [comment]
ok, now I think I got it... your package for download seems to miss something.. I did a fresh download of the zip file and this error occurred. now I just replaced my old mediatagger folder with the new files and it works like it should. so I think there are some files missing in the current zip archive

**Comment by ccjensen** [comment]
weird. I have removed the download link in the zip file and replaced it with instructions on how to find the one that github provides (in case that was the problem).
Thanks for letting me know the authentication/login stuff works!

**Comment by jdipper** [comment]
I'm getting the same issue. I think what Tigrecito was saying is that he copied the files from the current package on top of an old one (not sure which one).

Any ideas what's going wrong?

**Comment by Tigrecito** [comment]
yes, you are right. I just copied the files from the current archive into my old folder and replaced all files with the new ones.. this resolved the issue -> so it seems that there are some files missing in the current archive, which are needed and were present in a previous version.

**Comment by ccjensen** [comment]
I think I fixed this 17 hours ago, could you guys check and make sure a fresh copy now works?

**Comment by jdipper** [comment]
Yeap, works like a charm :-)

**Comment by ccjensen** [comment]
Awesome, thanks!

**Comment by ArnaudFeld** [comment]
I get this Error:

_Traceback (most recent call last):
  File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 297, in <module>
    sys.exit(main())
  File "/Volumes/Thor/PlexMediaTagger/plexmediatagger.py", line 254, in main
    section_processor.process_section(section_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 38, in process_section
    self.process_movie_section_element(section_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 141, in process_movie_section_element
    selected_movie_items = self.get_selection_for_media_container_element(movies_media_container_element)
  File "/Volumes/Thor/PlexMediaTagger/SectionProcessor.py", line 67, in get_selection_for_media_container_element
    list_of_items = [MovieItem(self.opts, item) for item in media_container_element.getchildren()]
  File "/Volumes/Thor/PlexMediaTagger/Items/MovieItem.py", line 17, in __init__
    self.media_items = [MediaItem(self.opts, self, media_element) for media_element in self.video.findall("Media")]
  File "/Volumes/Thor/PlexMediaTagger/Items/MediaItem.py", line 23, in __init__
    self.part_items = [PartItem(self.opts, self, part_element) for part_element in self.media_element.findall("Part")]
  File "/Volumes/Thor/PlexMediaTagger/Items/PartItem.py", line 23, in __init__
    self.file_path = normalize('NFC', unquote(file_path).decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 55: ordinal not in range(128)_

Any Hints?
